service: report-aggregators

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpack:
    includeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: development
  region: eu-west-1
  environment:
    ENV: ${file(config.${self:provider.stage}.json):ENV}

functions:
  action:
    handler: handler.action
    description: lambda boilerplate
    name: ${self:provider.stage}-lambda-boilerplate
    events:
